### ISSUE TITLE
How is this different from rtmp-module from vod perspective?

### ISSUE THREAD

**Issue by mertemin** [arut/nginx-ts-module#15]
nginx/video streaming noob here. I am trying to figure out the best way to stream videos from mp4 files on top of an nginx server. I'd like to support both browsers and mobile devices.

I have looked at rtmp-module and this one. How are they different from video on demand perspective? Looks like this one module works on top of HTTP while the other RTMP. Besides the protocol difference, what are pros and cons?

**Comment by arut** [comment]
Both modules do not support vod has or dash. The rtmp modules supports vod rtmp however. In fact you can just serve mp4 from nginx via http. Browsers use http range to request specific parts of mp4.
