### ISSUE TITLE
Is it possible to set receiving MPEG-TS over UDP?

### ISSUE THREAD

**Issue by mrnmilutinovic** [arut/nginx-ts-module#17]
Hello, 

I have encoders that are currently flooding the network using UDP multicast, and I'm trying to set this module up to receive MPEG-TS over UDP and then stream HLS. Is this possible or do I have to come up with some sort mechanism to overcome this? 

Thanks,

**Comment by arut** [comment]
I've made an approach to adding TS streaming to stream (TCP/UDP proxy). TCP is already working with some minor issues, but UDP has an issue which is hard to address. And not only in this module, but in nginx itself. Nginx currently cannot route all datagrams from a client (by this I mean address:port tuple) to one stream session. They are considered separate datagrams and are handled independently in different sessions and probably in different workers. There are some approaches to this problem but none of them is perfect.

**Comment by mrnmilutinovic** [comment]
Thanks for a prompt reply and clarification

**Comment by garybruckheimer** [comment]
What about when we switch to SRT instead of UDP? SRT is based on UDT. This protocol give uns more stable streaming,less jitter and it is firewall friendly. On top we have low latency.

Source:
https://github.com/Haivision/srt

**Comment by arut** [comment]
@garybruckheimer I didn't try it. Maybe I will some day.
