### ISSUE TITLE
Ошибка при сборке 

### ISSUE THREAD

**Issue by okatkov** [arut/nginx-ts-module#2]
использую версию nginx 1.12.0
при сборке появляется ошибка:

`
In file included from /usr/src/nginx-ts-module//src/ngx_ts_avc.c:8:0:    
/usr/src/nginx-ts-module//src/ngx_ts_avc.c: In function ‘ngx_ts_avc_read’:
src/core/ngx_core.h:101:37: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                     ^
/usr/src/nginx-ts-module//src/ngx_ts_avc.c:60:13: note: in expansion of macro ‘ngx_min’
         k = ngx_min(8 - br->shift, n);
             ^
src/core/ngx_core.h:101:54: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
 #define ngx_min(val1, val2)  ((val1 > val2) ? (val2) : (val1))
                                                      ^
/usr/src/nginx-ts-module//src/ngx_ts_avc.c:60:13: note: in expansion of macro ‘ngx_min’
         k = ngx_min(8 - br->shift, n);
             ^
cc1: all warnings being treated as errors
objs/Makefile:1195: recipe for target 'objs/addon/src/ngx_ts_avc.o' failed
make[1]: *** [objs/addon/src/ngx_ts_avc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
objs/Makefile:1181: recipe for target 'objs/addon/src/ngx_ts_dash.o' failed
make[1]: *** [objs/addon/src/ngx_ts_dash.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.12.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by arut** [comment]
Спасибо, исправил.
