### ISSUE TITLE
Play TS. Is this possible?

### ISSUE THREAD

**Issue by mesouug** [arut/nginx-ts-module#22]
Good day.

Does it possible to play TS stream without any conversion to HLS or DASH?

Thanks,
Mikhail.

**Comment by arut** [comment]
It's up to your player. Browsers aren't usually capable of that.

**Comment by mesouug** [comment]
No. I meant not to play HLS or DASH but rather play stream as is. For example I can use ffmpeg to push TS stream to module. Can I play this stream  with another ffmpeg using same URL as used to push the stream similar to rtmp module. For example to feed multiple clients with raw TS.

**Comment by arut** [comment]
Oh, I get it. No, currently it's not supported and probably will never be. However I will probably support (push) exec which will receive mpeg-ts on stdin. This will probably solve most issues.
