### ISSUE TITLE
dropping unexpected TS packet pid:0x%04uxd

### ISSUE THREAD

**Issue by quattre** [arut/nginx-ts-module#26]
Hi!
I'm getting this error "dropping unexpected TS packet pid:0x%04uxd" while executing this ffmpeg command: 
sudo ffmpeg -i udp://239.20.20.4:5004 -vsync 1 -async 1 -map 0:0 -map 0:1 -map 0:2 -c:v copy -c:a aac -f mpegts http://127.0.0.1:1500/publish/la1hd

¿can somebody help me to know what I'm doing wrong?
Thanks!

**Comment by gdrbyKo1** [comment]
It's just a piece of information, not an actual error. I tend to see a lot of these messages in the log as well, regardless of the settings I use when publishing with ffmpeg (haven't tried using some other publishing software), but as far as I know, these don't affect the stream in any way, ie. I can see no glitches, skips, or gaps. If the message bothers you, you could just set your error log level to `notice` or higher, so nginx doesn't clutter your log with these infos anymore.

**Comment by arut** [comment]
@gdrbyKo1 is right.  There can be a plenty of packets whose type not supported by the ts module, which carry additional information about the media stream. These packets are safely skipped and reported for debugging purposes.
