### ISSUE TITLE
Publish multiple streams dynamically

### ISSUE THREAD

**Issue by cypreess** [arut/nginx-ts-module#28]
Can I somehow dynamically manage streams that server is accepting to be published?

The problem I am trying to solve is a system that each user can open its own stream at any given moment, I am expecting to pass him a URL to publish a video. This would require Nginx to accept any new incoming stream and automatically create /media directory structure for it. I can sign URLs so I would be sure that only URLs generated from my system are valid new streams to handle.

**Comment by arut** [comment]
@cypreess, stream is published by a usual HTTP request, so you can use all the variety of nginx http features to limit access and make sure client is allowed to access the URL.
For example, you can use nginx [secure_link](http://nginx.org/en/docs/http/ngx_http_secure_link_module.html#secure_link) or [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html#auth_request).
