### ISSUE TITLE
nginx-rtmp-module vs. nginx-ts-module

### ISSUE THREAD

**Issue by rgordeev** [arut/nginx-ts-module#4]
Could you please explain key advantages for this module over nginx-rtmp-module? Are they comparable at all? Could I use them both at the same time? And I would very appreciate you if you explain then it is preferable to use each of them in details.

**Comment by TheTucan** [comment]
This is for dash and hls, whereas his rtmp module includes... Rtmp.

**Comment by rgordeev** [comment]
Thanks! I've got it from the module name ;)
I would like to know are there any benefits when I publish media stream (e.g. from ffmpeg) via nginx-ts-module (supposed I'm going to read it via hls/mpeg dash)?

**Comment by rgordeev** [comment]
I've made two docker containers to compare latency for rtmp-module and ts-module https://github.com/2chat.  And ts-module failed this simple test with more than 5 times worse result. I mean latency for ts-module was almost 50 seconds and for rtmp-module near 10 seconds. Did I make something wrong? Would appreciate for any ideas how to improve ;)

**Comment by arut** [comment]
The nginx-ts-module works on top of HTTP and lets you use all the variety of nginx HTTP features. The primary goal of the module is HLS and DASH which is what most people need these days. The ts module is much simpler than the the rtmp module and has way less features so far. Overall, nginx-ts-module is a simple solution for a typical case of live HLS/DASH generation.

PS: There should be no noticeable difference in latency between the modules.
