### ISSUE TITLE
DASH: gaps between segments with audio only

### ISSUE THREAD

**Issue by Jamie0** [arut/nginx-ts-module#5]
This issue seems to exist with nginx-rtmp-module, too.

When playing the DASH manifest in dash.js or Shaka player, there are gaps between the segments. These gaps don't occur when playing back the HLS manifest, hinting at a problem in the segmentation. 

The problem doesn't seem to happen when I send the server both audio and video. 

I'm using the following config

	server {

		listen localhost:8081;
		server_name localhost;
		
		root /tmp/htdocs;

		client_max_body_size 0;

		location /ingest {

			allow 127.0.0.1;
			deny all;
		
			ts;
			ts_hls path=/tmp/htdocs/egest/a segment=10s segments=30;
			ts_dash path=/tmp/htdocs/egest/b segment=10s segments=30;
		
		}

		location / {
			add_header Access-Control-Allow-Origin *;
		}

	}

And this ffmpeg command:

`ffmpeg -i https://stream.cor.insanityradio.com/insanity_test.mp3 -c:a libfdk_aac -f mpegts http://127.0.0.1:8081/ingest`

Problem occurs regardless of what codec I use (HE/LE have the issue).

**Comment by Jamie0** [comment]
Our use case is online radio simulcast, so being able to serve just audio is quite important.

**Comment by arut** [comment]
@Jamie0 do you have this issue in a particular browser or in all browsers? The reason I'm asking is I have audio gap issue in Safari with dash.js as well, which I believe is unrelated to the dash stream itself. The same stream plays in other browsers just fine.

**Comment by Jamie0** [comment]
At the time I tested the issue in all browsers and the issue seemed apparent. I will update later today as I'm going to try and investigate this afternoon.

**Comment by Jamie0** [comment]
I can no longer replicate this issue. Closed.
