### ISSUE TITLE
How to use OBS or other push device to flow to nginx-ts-module module?

### ISSUE THREAD

**Issue by Tinywan** [arut/nginx-ts-module#6]
##  How to nginx-ts-module push?
+  How to use OBS or other push device to flow to nginx-ts-module module, like nginx-RTMP-module
+  try push ,is error `http://127.0.0.1:8000/publish/123456`
    
##  nginx-rtmp-module Push
`rtmp://up.quanmin.tv/live/123456`

**Comment by emreuenal** [comment]
same problem... any advice?

**Comment by TimIsOverpowered** [comment]
exec ffmpeg -i rtmp://127.0.0.1:1935/$app/$name -bsf:v h264_mp4toannexb -c copy -f mpegts https://URL/publish

**Comment by Tinywan** [comment]
@TimIsOverpowered Hi!
 Not ffmpeg flow, but with equipment or push the flow of software, such as: OBS, equipment box

**Comment by TimIsOverpowered** [comment]
OBS uses rtmp. you can push from OBS > nginx-rtmp > nginx-ts with that code.

**Comment by Tinywan** [comment]
@TimIsOverpowered 
Thank you for your answer! This can be

**Comment by musclewizard** [comment]
also:  you can push mpegts from obs using the record feature:

Settings -> Output -> set Output Mode to Advanced -> Recording -> Custom Output (FFmpeg) -> FFmpeg Output Type -> Output to URL, File path or URL -> http://yourserver/input_path and Muxer Settings -f mpegts should do the trick.
