### ISSUE TITLE
Не проигрывается  dash

### ISSUE THREAD

**Issue by infoqrakz** [arut/nginx-ts-module#8]
Сделал все по инструкции 
hls генерится и играет
c  dash след проблема 
в папке появляются манифест и файлы 
но проиграть не могу пробовал как плеером из примера 
так и http://dashif.org/reference/players/javascript/1.3.0/samples/dash-if-reference-player/index.html

возможно связано с тем что в  манифесте 

            media="$RepresentationID$.$Time$.mp4"
            initialization="$RepresentationID$.init.mp4">

P.S. Спасибо за Вашу работу.

полный манифест ниже 
<?xml version="1.0"?>
<MPD
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="urn:mpeg:DASH:schema:MPD:2011"
    xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 DASH-MPD.xsd"
    type="dynamic"
    availabilityStartTime="2017-08-26T04:49:40Z"
    publishTime="2017-08-26T05:00:33Z"
    minimumUpdatePeriod="PT10S"
    minBufferTime="PT10S"
    timeShiftBufferDepth="PT41S"
    profiles="urn:hbbtv:dash:profile:isoff-live:2012,urn:mpeg:dash:profile:isoff-live:2011">
  <Period
      id="0"
      start="PT0S">
    <AdaptationSet
        segmentAlignment="true"
        mimeType="video/mp4">
      <Representation
          id="256"
          codecs="avc1.4D401E"
          bandwidth="202254">
        <SegmentTemplate
            timescale="90000"
            media="$RepresentationID$.$Time$.mp4"
            initialization="$RepresentationID$.init.mp4">
          <SegmentTimeline>
            <S t="54621584" d="900018"/>
            <S t="55521602" d="900016"/>
            <S t="56421618" d="900018"/>
            <S t="57321636" d="900018"/>
            <S t="58221654" d="900018"/>
            <S t="59121672" d="900016"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>

**Comment by arut** [comment]
Попробуйте посмотреть что dash.js пишет в js лог. В приведенном вами куске манифеста ничего странного не вижу.  Init-файл у вас сгенерился?

**Comment by infoqrakz** [comment]
По логу понял что проблема с 
No 'Access-Control-Allow-Origin' header 
--- 
добавил   add_header Access-Control-Allow-Origin *;   
в nginx

**Comment by arut** [comment]
@infoqrakz так все заработало?

**Comment by infoqrakz** [comment]
да
